In [2]:
import numpy as np

## 1. DataTypes and Attributes

In [31]:
# NumPy's maint datatype id ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [5]:
type(a1)

numpy.ndarray

In [91]:
a2 = np.array([[1,2,3.3],
              [4,5.5,6],])
a2 

array([[1. , 2. , 3.3],
       [4. , 5.5, 6. ]])

In [33]:
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
                [[10,11,12],
                [12,13,14],
                [15,16,17]]])

In [8]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [12, 13, 14],
        [15, 16, 17]]])

In [9]:
a1.shape

(3,)

In [10]:
a2.shape

(2, 3)

In [11]:
a3.shape

(2, 3, 3)

In [12]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [14]:
a1.dtype

dtype('int32')

In [16]:
a2.dtype

dtype('float64')

In [17]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [18]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

## 2. Creating arrays

In [5]:
sample_array = np.array([1, 2, 3])
sample_array
sample_array.dtype

dtype('int32')

In [67]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
ones.dtype

dtype('float64')

In [22]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [9]:
random_array = np.random.randint(0, 10, size=(3,5))
random_array

array([[2, 5, 2, 6, 9],
       [9, 0, 4, 1, 6],
       [1, 3, 6, 0, 8]])

In [12]:
random_array.size

15

In [13]:
random_array.shape

(3, 5)

In [14]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.78022549, 0.56648045, 0.23693729],
       [0.21571699, 0.40147496, 0.11021412],
       [0.90096134, 0.71715591, 0.72384052],
       [0.54322291, 0.06178024, 0.95988451],
       [0.34381965, 0.1637677 , 0.63094643]])

In [21]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.68447376, 0.92416303, 0.95008499],
       [0.06930552, 0.76202888, 0.12422678],
       [0.57640177, 0.71721195, 0.06752466],
       [0.23235753, 0.52546008, 0.18136021],
       [0.0337893 , 0.40249373, 0.99282213]])

In [27]:
# Pseudo-random numbers
np.random.seed(3)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[8, 9, 3],
       [8, 8, 0],
       [5, 3, 9],
       [9, 5, 7],
       [6, 0, 4]])

## 3. Viewing arrays and matrices

In [28]:
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[7, 8, 1],
       [6, 2, 2],
       [1, 3, 5],
       [8, 1, 8],
       [7, 8, 1]])

In [29]:
np.unique(random_array_4)

array([1, 2, 3, 5, 6, 7, 8])

In [34]:
a1

array([1, 2, 3])

In [35]:
a2

array([[1. , 2. , 3.3],
       [4. , 5.5, 6. ]])

In [36]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [12, 13, 14],
        [15, 16, 17]]])

In [37]:
a1[0]

1

In [38]:
a2[0]

array([1. , 2. , 3.3])

In [39]:
a3.shape

(2, 3, 3)

In [40]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
 a3[0][1]

array([4, 5, 6])

In [42]:
a3[0][1][1]

5

In [43]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [12, 13]]])

In [44]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[0, 5, 4, 1, 5],
         [4, 7, 6, 0, 0],
         [9, 2, 4, 5, 8],
         [8, 7, 5, 1, 1]],

        [[1, 5, 5, 7, 4],
         [3, 0, 0, 0, 0],
         [2, 2, 7, 0, 5],
         [0, 1, 4, 1, 2]],

        [[2, 4, 8, 0, 6],
         [0, 4, 1, 5, 1],
         [8, 8, 7, 0, 0],
         [9, 1, 7, 8, 7]]],


       [[[4, 0, 0, 4, 3],
         [0, 8, 2, 7, 2],
         [1, 3, 2, 4, 1],
         [2, 2, 7, 3, 4]],

        [[1, 6, 7, 9, 1],
         [0, 0, 5, 8, 4],
         [8, 8, 3, 4, 9],
         [2, 5, 4, 7, 9]],

        [[1, 9, 0, 7, 4],
         [8, 8, 4, 1, 4],
         [0, 5, 6, 7, 0],
         [7, 8, 1, 5, 3]]]])

In [45]:
a4.shape

(2, 3, 4, 5)

In [46]:
a4.ndim

4

In [61]:
# Get the first 4 numbers of the inner most arrays
a4[:, :, :, :4]

array([[[[0, 5, 4, 1],
         [4, 7, 6, 0],
         [9, 2, 4, 5],
         [8, 7, 5, 1]],

        [[1, 5, 5, 7],
         [3, 0, 0, 0],
         [2, 2, 7, 0],
         [0, 1, 4, 1]],

        [[2, 4, 8, 0],
         [0, 4, 1, 5],
         [8, 8, 7, 0],
         [9, 1, 7, 8]]],


       [[[4, 0, 0, 4],
         [0, 8, 2, 7],
         [1, 3, 2, 4],
         [2, 2, 7, 3]],

        [[1, 6, 7, 9],
         [0, 0, 5, 8],
         [8, 8, 3, 4],
         [2, 5, 4, 7]],

        [[1, 9, 0, 7],
         [8, 8, 4, 1],
         [0, 5, 6, 7],
         [7, 8, 1, 5]]]])

In [62]:
# Slicing 
a4[:1, :2, 1:3, :4]

array([[[[4, 7, 6, 0],
         [9, 2, 4, 5]],

        [[3, 0, 0, 0],
         [2, 2, 7, 0]]]])

## 4. Manipulating and comparing arrays

### Arithmetic

In [65]:
a1

array([1, 2, 3])

In [68]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [69]:
a1 + ones

array([[2., 3., 4.],
       [2., 3., 4.]])

In [70]:
a1 - ones

array([[0., 1., 2.],
       [0., 1., 2.]])

In [71]:
a1 * ones

array([[1., 2., 3.],
       [1., 2., 3.]])

In [92]:
 a2

array([[1. , 2. , 3.3],
       [4. , 5.5, 6. ]])

In [93]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [94]:
a2_reshaped = np.reshape(a2, (2,3,1))
a2_reshaped

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5.5],
        [6. ]]])

In [95]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [12, 13, 14],
        [15, 16, 17]]])

In [96]:
a2_reshaped * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 66. ,  71.5,  77. ],
        [ 90. ,  96. , 102. ]]])

In [97]:
a1 / ones

array([[1., 2., 3.],
       [1., 2., 3.]])

In [100]:
a2

array([[1. , 2. , 3.3],
       [4. , 5.5, 6. ]])

In [98]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 30.25, 36.  ]])

In [99]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 30.25, 36.  ]])

In [101]:
np.add(a1, ones)

array([[2., 3., 4.],
       [2., 3., 4.]])

In [102]:
a1 % 2

array([1, 0, 1], dtype=int32)

In [103]:
a2 % 2

array([[1. , 0. , 1.3],
       [0. , 1.5, 0. ]])

In [104]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [105]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation

Aggregation - performing the same operation on a number of things

In [106]:
li_list = [1,2,3]

In [108]:
li_list

[1, 2, 3]

In [111]:
type(li_list)

list

In [110]:
sum(li_list)

6

In [113]:
np.sum(a1)

6

In [114]:
type(a1)

numpy.ndarray

Use Python's methods (`sum()`) on Python datatypes and use NumPy's methods on NumPy arrays (`np.sum()`).

In [116]:
massive_array = np.random.random(100000)
massive_array[:10]

array([0.01032505, 0.64331144, 0.31552015, 0.15790592, 0.46576606,
       0.91445717, 0.01700614, 0.94295837, 0.66388377, 0.35358019])

In [117]:
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # NumPy's np.sum()

10.8 ms ± 43.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
62.8 µs ± 697 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [118]:
a2

array([[1. , 2. , 3.3],
       [4. , 5.5, 6. ]])

In [119]:
np.mean(a2)

3.6333333333333333

In [120]:
np.max(a2)

6.0

In [121]:
np.min(a2)

1.0

In [122]:
# The Standard Deviation is a measure of how spread out numbers are.
np.std(a2)

1.7763883459298968

In [123]:
# Variance is a measure of the average degree to which each number is divverent to the mean
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers
np.var(a2)

3.155555555555555

In [124]:
# Standart deviation = squareroot of variance
np.sqrt(np.var(a2))

1.7763883459298968