# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [3]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [5]:
# Create a 1-dimensional NumPy array using np.array()

a1 = np.array([1,2,30])
# Create a 2-dimensional NumPy array using np.array()

a2 = np.array([[1,2,3],
               [4,5,6]])
# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1,2,3],
                [4,5,6]],
                [[7,8,9],
                 [10,11,12]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [47]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.ndim, a1.shape, a1.dtype, a1.size, type(a1)

(1, (3,), dtype('int32'), 3, numpy.ndarray)

In [48]:
# Attributes of 2-dimensional array
a2.ndim, a2.shape, a2.dtype, a2.size, type(a2)

(2, (2, 3), dtype('int32'), 6, numpy.ndarray)

In [49]:
# Attributes of 3-dimensional array
a3.ndim, a3.shape, a3.dtype, a3.size, type(a3)

(3, (2, 2, 3), dtype('int32'), 12, numpy.ndarray)

In [52]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
a2_df = pd.DataFrame(a2, index=["Day 1", "Day 2"], columns=["Value 1", "Value 2", "Value 3"])
a2_df = pd.DataFrame(a2)
a2_df

0  1  2
0  1  2  3
1  4  5  6

In [19]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [21]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [23]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0, 100, 3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [24]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
rand_array = np.random.randint(0, 10, size=(7, 2))
rand_array

array([[9, 3],
       [7, 2],
       [9, 7],
       [8, 6],
       [3, 5],
       [1, 4],
       [0, 1]])

In [26]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
rand_array_1 = np.random.random((3, 5))
rand_array_1

array([[0.96265297, 0.06781769, 0.44677655, 0.91743691, 0.18791327],
       [0.81244933, 0.26865432, 0.30634773, 0.8724705 , 0.67938121],
       [0.87722696, 0.7962309 , 0.06128083, 0.20847907, 0.43587652]])

In [35]:
# Set the random seed to 42
seed = np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
rand_array_2 = np.random.randint(0, 10, size=(4,6))
rand_array_2

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [60]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
rand_array_3 = np.random.randint(1, 10, size=(3, 7))

# Find the unique numbers in the array you just created
np.unique(rand_array_3), rand_array_3 

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[5, 6, 3, 9, 5, 8, 1],
        [5, 3, 1, 4, 5, 7, 1],
        [3, 2, 9, 6, 3, 8, 8]]))

In [68]:
# Find the 0'th index of the latest array you created
rand_array_3[0]

array([5, 6, 3, 9, 5, 8, 1])

In [69]:
# Get the first 2 rows of latest array you created
rand_array_3[:2]

array([[5, 6, 3, 9, 5, 8, 1],
       [5, 3, 1, 4, 5, 7, 1]])

In [88]:
# Get the first 2 values of the first 2 rows of the latest array
rand_array_3[:2, :2]

array([[5, 6],
       [5, 3]])

In [91]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
ones_1 = np.ones((3,5))
rand_array_4 = np.random.randint(0, 10, size=(3,5))
ones_1, rand_array_4

(array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]),
 array([[9, 2, 1, 8, 7],
        [9, 6, 8, 3, 3],
        [0, 7, 2, 6, 1]]))

In [92]:
# Add the two arrays together
ones_1 + rand_array_4

array([[10.,  3.,  2.,  9.,  8.],
       [10.,  7.,  9.,  4.,  4.],
       [ 1.,  8.,  3.,  7.,  2.]])

In [96]:
# Create another array of ones of shape (5, 3)
ones_2 = np.ones((5,3))

In [97]:
# Try add the array of ones and the other most recent array together
ones_2.T + rand_array_4

array([[10.,  3.,  2.,  9.,  8.],
       [10.,  7.,  9.,  4.,  4.],
       [ 1.,  8.,  3.,  7.,  2.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [100]:
# Create another array of ones of shape (3, 5)
ones_3 = np.ones((3,5))

In [101]:
# Subtract the new array of ones from the other most recent array
rand_array_4 - ones_3

array([[ 8.,  1.,  0.,  7.,  6.],
       [ 8.,  5.,  7.,  2.,  2.],
       [-1.,  6.,  1.,  5.,  0.]])

In [102]:
# Multiply the ones array with the latest array
ones_3 * rand_array_4

array([[9., 2., 1., 8., 7.],
       [9., 6., 8., 3., 3.],
       [0., 7., 2., 6., 1.]])

In [103]:
# Take the latest array to the power of 2 using '**'
rand_array_4 **2

array([[81,  4,  1, 64, 49],
       [81, 36, 64,  9,  9],
       [ 0, 49,  4, 36,  1]])

In [105]:
# Do the same thing with np.square()
np.square(rand_array_4)

array([[81,  4,  1, 64, 49],
       [81, 36, 64,  9,  9],
       [ 0, 49,  4, 36,  1]])

In [106]:
# Find the mean of the latest array using np.mean()
np.mean(rand_array_4)

4.8

In [107]:
# Find the maximum of the latest array using np.max()
np.max(rand_array_4)

9

In [108]:
# Find the minimum of the latest array using np.min()
np.min(rand_array_4)

0

In [109]:
# Find the standard deviation of the latest array
np.std(rand_array_4)

3.0811253355443577

In [110]:
# Find the variance of the latest array
np.var(rand_array_4)

9.493333333333332

In [112]:
rand_array_4.shape

(3, 5)

In [111]:
# Reshape the latest array to (3, 5, 1)
rand_array_4.reshape(3, 5, 1)

array([[[9],
        [2],
        [1],
        [8],
        [7]],

       [[9],
        [6],
        [8],
        [3],
        [3]],

       [[0],
        [7],
        [2],
        [6],
        [1]]])

In [113]:
# Transpose the latest array
rand_array_4.T

array([[9, 9, 0],
       [2, 6, 7],
       [1, 8, 2],
       [8, 3, 6],
       [7, 3, 1]])

What does the transpose do?

In [118]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr1 = np.random.randint(0, 10, size=(3, 3))
arr2 = np.random.randint(0, 10, size=(3, 2))
arr1, arr2

(array([[2, 6, 7],
        [3, 1, 9],
        [2, 0, 7]]),
 array([[2, 9],
        [6, 9],
        [4, 9]]))

In [119]:
# Perform a dot product on the two newest arrays you created
arr1.dot(arr2)

array([[ 68, 135],
       [ 48, 117],
       [ 32,  81]])

In [121]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr3 = np.random.randint(0, 10, size=(4, 3))
arr4 = np.random.randint(0, 10, size=(4, 3))

In [122]:
# Perform a dot product on the two newest arrays you created
arr3.dot(arr4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [123]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
arr3.dot(arr4.T)

array([[ 34,  70,  34,  36],
       [ 34, 115,  64,  56],
       [ 14, 107,  68,  48],
       [ 40, 133,  70,  68]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [124]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
mat1 = np.random.randint(0, 10, size=(2, 4))
mat2 = np.random.randint(0, 10, size=(2, 4))
mat1, mat2

(array([[9, 9, 5, 4],
        [3, 1, 3, 9]]),
 array([[9, 2, 9, 0],
        [7, 4, 3, 7]]))

In [125]:
# Compare the two arrays with '>'
mat1 > mat2

array([[False,  True, False,  True],
       [False, False, False,  True]])

What happens when you compare the arrays with `>`?

In [126]:
# Compare the two arrays with '>='
mat1 >= mat2

array([[ True,  True, False,  True],
       [False, False,  True,  True]])

In [127]:
# Find which elements of the first array are greater than 7
mat1 > 7

array([[ True,  True, False, False],
       [False, False, False,  True]])

In [128]:
# Which parts of each array are equal? (try using '==')
mat1 == mat2

array([[ True, False, False, False],
       [False, False,  True, False]])

In [129]:
# Sort one of the arrays you just created in ascending order
np.sort(mat1)

array([[4, 5, 9, 9],
       [1, 3, 3, 9]])

In [130]:
# Sort the indexes of one of the arrays you just created
np.argsort(mat1)

array([[3, 2, 0, 1],
       [1, 0, 2, 3]], dtype=int64)

In [132]:
mat1

array([[9, 9, 5, 4],
       [3, 1, 3, 9]])

In [131]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(mat1)

0

In [133]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(mat1)

5

In [137]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(mat1, axis=1)

array([0, 3], dtype=int64)

In [138]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(mat1, axis=0)

array([1, 1, 1, 0], dtype=int64)

In [142]:
# Create an array of normally distributed random numbers
np.random.randn(3, 5, 4)

array([[[-1.15551591,  1.57011062, -1.12495174,  1.28192038],
        [-0.02842146, -1.71642445, -1.04296139,  1.32647167],
        [ 0.44864867, -0.07873168, -2.21676105,  1.38956634],
        [ 1.8704239 ,  1.68801703, -0.61524522,  0.38279947],
        [ 0.49214103, -1.52745263,  0.18049251,  1.07104152]],

       [[ 0.76447824, -1.11116381, -0.86261512,  0.79059399],
        [ 0.63285244, -2.25415868, -2.45659315, -0.07653206],
        [-0.58965286, -0.29830122, -0.41129059,  0.98402354],
        [ 0.10356808,  0.26763601, -1.34231283, -3.36409553],
        [ 1.12354178,  2.14320519, -0.34258887,  0.24931454]],

       [[ 0.32451832,  1.67529325,  0.88898429,  0.49606423],
        [ 0.05557216,  0.06023292, -1.4394616 , -0.38348753],
        [ 0.88620197, -0.23370318,  0.04435056, -1.17612748],
        [ 0.4455069 , -1.46175666,  0.28988281, -0.18722496],
        [-1.74328525,  1.06947795, -0.16386526,  1.86077805]]])

In [154]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 50, retstep=True)

(array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
          9.08163265,  11.10204082,  13.12244898,  15.14285714,
         17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
         25.24489796,  27.26530612,  29.28571429,  31.30612245,
         33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
         41.40816327,  43.42857143,  45.44897959,  47.46938776,
         49.48979592,  51.51020408,  53.53061224,  55.55102041,
         57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
         65.65306122,  67.67346939,  69.69387755,  71.71428571,
         73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
         81.81632653,  83.83673469,  85.85714286,  87.87755102,
         89.89795918,  91.91836735,  93.93877551,  95.95918367,
         97.97959184, 100.        ]),
 2.020408163265306)

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.